import { Post, BannerItem, ShopItem, ActionItem, ProfileData, InsightArticle, FaithChallenge } from "@/types";

// ── Insight & Event 배너 ──
export const bannerItems: BannerItem[] = [
  {
    id: "b1",
    category: "insight",
    label: "INSIGHT",
    title: "서아프리카 선교지에서 전하는\n긴급 기도제목",
    subtitle: "현지 선교사 인터뷰 · 5분 읽기",
    accent: "#FF5C1A",
  },
  {
    id: "b2",
    category: "event",
    label: "EVENT · D-12",
    title: "2026 전국 청년 연합 집회\n참가 신청 오픈",
    subtitle: "3월 15일 · 여의도 순복음교회",
    accent: "#FFD600",
  },
  {
    id: "b3",
    category: "insight",
    label: "TREND",
    title: "크리스천 MZ세대,\n'건전한 놀이 문화'를 만들다",
    subtitle: "SOLT 매거진 · 4분 읽기",
    accent: "#FF5C1A",
  },
];

// ── Play & Learn 모임 ──
export const mockPosts: Post[] = [
  {
    id: "1",
    type: "play",
    title: "토요일 오전 강남 풋살 팟",
    description: "매주 토요일 오전, 함께 뛰어요! 실력 무관.",
    date: "3/7 (토) 10:00",
    location: "잠실 실내체육관",
    region: "서울",
    maxParticipants: 12,
    currentParticipants: 8,
    tag: "운동",
    emoji: "⚽",
    status: "모집중",
    host: { id: "u1", name: "준혁", isVerified: true },
  },
  {
    id: "2",
    type: "learn",
    title: "평신도를 위한 기독교 상담학",
    description: "상담의 기초부터 실전까지 배웁니다.",
    date: "매주 화 19:30",
    location: "온라인 (Zoom)",
    region: "온라인",
    maxParticipants: 30,
    currentParticipants: 15,
    tag: "클래스",
    emoji: "📖",
    status: "모집중",
    host: { id: "u2", name: "수빈", isVerified: true },
  },
  {
    id: "3",
    type: "play",
    title: "성수동 카페 탐방 & 독서 모임",
    description: "예쁜 카페에서 함께 책 읽고 이야기 나눠요.",
    date: "3/8 (일) 15:00",
    location: "성수동 일대",
    region: "서울",
    maxParticipants: 6,
    currentParticipants: 5,
    tag: "독서",
    emoji: "📚",
    status: "마감임박",
    host: { id: "u3", name: "민지", isVerified: false },
  },
  {
    id: "4",
    type: "learn",
    title: "찬양 기타 워크숍: 코드 기초",
    description: "CCM 반주에 필요한 기타 코드와 주법.",
    date: "3/15 (토) 14:00",
    location: "홍대 연습실",
    region: "서울",
    maxParticipants: 6,
    currentParticipants: 2,
    tag: "찬양",
    emoji: "🎸",
    status: "모집중",
    host: { id: "u4", name: "재원", isVerified: true },
  },
  {
    id: "5",
    type: "play",
    title: "한강 러닝 크루 수요 정모",
    description: "수요일 저녁 한강 5km. 페이스 자유!",
    date: "매주 수 19:00",
    location: "여의도 한강공원",
    region: "서울",
    maxParticipants: 20,
    currentParticipants: 12,
    tag: "러닝",
    emoji: "🏃",
    status: "모집중",
    host: { id: "u5", name: "하은", isVerified: true },
  },
  {
    id: "6",
    type: "learn",
    title: "성경적 재정 관리 세미나",
    description: "성경적 재정 원칙과 가계부 작성법.",
    date: "3/22 (토) 10:00",
    location: "사랑의교회 세미나실",
    region: "서울",
    maxParticipants: 30,
    currentParticipants: 28,
    tag: "재정",
    emoji: "💰",
    status: "마감임박",
    host: { id: "u6", name: "성호", isVerified: true },
  },
  {
    id: "7",
    type: "play",
    title: "주일 오후 보드게임 모임",
    description: "예배 후 점심 먹고 보드게임 한 판!",
    date: "매주 일 13:00",
    location: "강남 보드게임 카페",
    region: "서울",
    maxParticipants: 8,
    currentParticipants: 8,
    tag: "친교",
    emoji: "🎲",
    status: "마감",
    host: { id: "u7", name: "도현", isVerified: true },
  },
  {
    id: "8",
    type: "learn",
    title: "영어로 읽는 NIV 성경 클래스",
    description: "NIV 성경을 함께 읽으며 영어 실력도 키워요.",
    date: "매주 목 20:00",
    location: "온라인 (Zoom)",
    region: "온라인",
    maxParticipants: 15,
    currentParticipants: 7,
    tag: "영어",
    emoji: "🌏",
    status: "모집중",
    host: { id: "u8", name: "예진", isVerified: true },
  },
  {
    id: "c1",
    type: "learn",
    title: "성경적 자녀 양육 실전 특강",
    description: "신앙 위에 세우는 가정 교육의 모든 것. 0-18세 연령별 맞춤 가이드 8주 과정.",
    date: "매주 토 10:00",
    location: "온라인 (Zoom)",
    region: "온라인",
    maxParticipants: 60,
    currentParticipants: 43,
    tag: "자녀양육",
    emoji: "👨‍👩‍👧",
    status: "모집중",
    host: { id: "c1", name: "이종훈 목사", isVerified: true },
  },
  {
    id: "c2",
    type: "learn",
    title: "기독교 세계관으로 읽는 현대 사회",
    description: "사회·문화·정치를 성경적 렌즈로 분석하는 6주 심층 강의. 실천적 크리스천을 위한 필수 과정.",
    date: "3/20 (목) 19:30",
    location: "사랑의교회 세미나실",
    region: "서울",
    maxParticipants: 40,
    currentParticipants: 28,
    tag: "기독교세계관",
    emoji: "🌍",
    status: "모집중",
    host: { id: "c2", name: "박성진 교수", isVerified: true },
  },
  {
    id: "c3",
    type: "learn",
    title: "크리스천 글로벌 인재 성장 과정",
    description: "신앙과 전문성을 겸비한 글로벌 리더 양성 12주 과정. 해외 취업·유학·선교적 직업관 포함.",
    date: "3/25 (화) 19:00",
    location: "온라인 (Zoom)",
    region: "온라인",
    maxParticipants: 30,
    currentParticipants: 17,
    tag: "글로벌인재",
    emoji: "🚀",
    status: "모집중",
    host: { id: "c3", name: "김지수 대표", isVerified: true },
  },
  {
    id: "c4",
    type: "learn",
    title: "기독교 대안학교 설립 가이드",
    description: "대안학교 설립부터 커리큘럼 설계, 인가 절차까지. 실제 운영자가 전하는 8주 실전 강의.",
    date: "4/5 (토) 10:00",
    location: "온라인 (Zoom)",
    region: "온라인",
    maxParticipants: 25,
    currentParticipants: 11,
    tag: "대안학교",
    emoji: "🏫",
    status: "모집중",
    host: { id: "c4", name: "최은영 원장", isVerified: true },
  },
  {
    id: "9",
    type: "play",
    title: "분당 수요 찬양 모임",
    description: "매주 수요일, 함께 찬양으로 한 주를 마무리해요.",
    date: "매주 수 20:00",
    location: "분당 카페 드림",
    region: "경기",
    maxParticipants: 15,
    currentParticipants: 9,
    tag: "찬양",
    emoji: "🎵",
    status: "모집중",
    host: { id: "u9", name: "지훈", isVerified: true },
  },
  {
    id: "10",
    type: "play",
    title: "인천 청년 봉사 모임",
    description: "인천 지역 독거 어르신 방문 봉사 함께해요.",
    date: "3/14 (토) 10:00",
    location: "인천 남구 일대",
    region: "인천",
    maxParticipants: 10,
    currentParticipants: 6,
    tag: "봉사",
    emoji: "🤲",
    status: "모집중",
    host: { id: "u10", name: "서연", isVerified: true },
  },
];

// ── Shop 큐레이션 ──
export const shopItems: ShopItem[] = [
  { id: "s1", title: "캘리그라피 말씀 엽서 세트", brand: "Grace Letter", price: "12,000원", tag: "문구", emoji: "✉️" },
  { id: "s2", title: "우드 십자가 북마크", brand: "Olive Craft", price: "8,500원", tag: "소품", emoji: "🔖" },
  { id: "s3", title: "데일리 큐티 저널 노트", brand: "SOLT Original", price: "15,000원", tag: "노트", emoji: "📓" },
  { id: "s4", title: "히브리어 타이포 머그컵", brand: "Shalom Studio", price: "18,000원", tag: "리빙", emoji: "☕" },
  { id: "s5", title: "CCM 플레이리스트 키링", brand: "Worship Goods", price: "6,000원", tag: "액세서리", emoji: "🎵" },
  { id: "s6", title: "에코백 'Salt & Light'", brand: "SOLT Original", price: "22,000원", tag: "패션", emoji: "👜" },
];

// ── Action 캠페인 ──
export const actionItems: ActionItem[] = [
  {
    id: "a1",
    title: "동아프리카 식수 프로젝트",
    description: "케냐 투르카나 지역 우물 건설을 위한 후원",
    currentAmount: 4200000,
    goalAmount: 10000000,
    unit: "원",
    dday: "D-23",
    category: "donation",
    emoji: "💧",
  },
  {
    id: "a2",
    title: "독거 어르신 도시락 배달",
    description: "서울 관악구 독거 어르신 100가구 주 2회 식사 지원",
    currentAmount: 78,
    goalAmount: 100,
    unit: "가구",
    dday: "D-7",
    category: "volunteer",
    emoji: "🍱",
  },
  {
    id: "a3",
    title: "미자립교회 난방비 지원",
    description: "강원도 소규모 교회 겨울 난방비 긴급 지원",
    currentAmount: 1800000,
    goalAmount: 3000000,
    unit: "원",
    dday: "D-15",
    category: "donation",
    emoji: "🔥",
  },
  {
    id: "a4",
    title: "청소년 학습 멘토링",
    description: "노원구 지역 청소년 1:1 학습 멘토링 자원봉사자 모집",
    currentAmount: 34,
    goalAmount: 50,
    unit: "명",
    dday: "D-10",
    category: "volunteer",
    emoji: "📚",
  },
  {
    id: "a5",
    title: "탄소 발자국 줄이기 챌린지",
    description: "21일 동안 크리스천 환경 실천 챌린지에 함께하세요",
    currentAmount: 1240,
    goalAmount: 3000,
    unit: "명",
    dday: "D-18",
    category: "campaign",
    emoji: "🌱",
  },
  {
    id: "a6",
    title: "예배 그래픽 재능기부",
    description: "미자립 교회를 위한 주보·배너·유튜브 썸네일 디자인 재능기부",
    currentAmount: 12,
    goalAmount: 20,
    unit: "교회",
    dday: "D-30",
    category: "talent",
    emoji: "🎨",
  },
];

// ── Faith Challenges ──
export const faithChallenges: FaithChallenge[] = [
  {
    id: "fc1", category: "bible", categoryLabel: "성경통독",
    title: "100일 성경 통독 챌린지",
    description: "매일 한 장씩, 100일 동안 신약성경을 통독합니다. 무리없이 쉬운 것부터 시작해요.",
    duration: "100일", totalDays: 100, emoji: "📖", color: "#0D2B4E",
    badgeEmoji: "📖", participants: 1247,
  },
  {
    id: "fc2", category: "prayer", categoryLabel: "기도 습관",
    title: "새벽 5분 중보기도 21일",
    description: "매일 새벽, 5분씩 타인을 위한 중보기도를 드립니다. 작은 기도가 세상을 바꿉니다.",
    duration: "21일", totalDays: 21, emoji: "🙏", color: "#5856D6",
    badgeEmoji: "🕊️", participants: 834,
  },
  {
    id: "fc3", category: "morning", categoryLabel: "미라클 모닝 큐티",
    title: "미라클 모닝 큐티 30일",
    description: "기상 후 30분, 말씀 묵상으로 하루를 시작하는 30일 큐티 습관 챌린지.",
    duration: "30일", totalDays: 30, emoji: "🌅", color: "#FF9500",
    badgeEmoji: "☀️", participants: 2150,
  },
  {
    id: "fc4", category: "growth", categoryLabel: "기독교적 자기계발",
    title: "크리스천 독서 마라톤 — 3권 완주",
    description: "한 달에 기독교 관련 책 3권 읽기. 신학서, 간증집, 리더십 도서를 망라합니다.",
    duration: "30일", totalDays: 30, emoji: "📚", color: "#34C759",
    badgeEmoji: "📚", participants: 567,
  },
];

// ── Insight Articles ──
export const insightArticles: InsightArticle[] = [
  {
    id: "ia1",
    category: "news",
    categoryLabel: "교계&사회뉴스",
    label: "MISSION NEWS",
    title: "서아프리카 선교지에서 전하는\n긴급 기도제목",
    subtitle: "이슬람 극단주의 위협 속 성도들의 신앙 — 현지 선교사 인터뷰",
    accent: "#0D2B4E",
    author: { name: "김성호 선교사", title: "서아프리카 말리 파송 선교사" },
    readTime: 5,
    keywords: ["선교", "아프리카", "기도", "박해"],
    featured: true,
  },
  {
    id: "ia2",
    category: "news",
    categoryLabel: "교계&사회뉴스",
    label: "CHURCH NEWS",
    title: "한국 교회 청년 이탈률,\n5년 만에 역전 조짐",
    subtitle: "2025 교회 출석 조사 — SOLT 세대가 만드는 변화",
    accent: "#0D2B4E",
    author: { name: "SOLT 편집부", title: "리서치 팀" },
    readTime: 4,
    keywords: ["청년", "한국교회", "통계", "MZ세대"],
  },
  {
    id: "ia3",
    category: "theology",
    categoryLabel: "신학&아카이브",
    label: "THEOLOGY",
    title: "팀 켈러의 신학이\n한국 교회에 남긴 것",
    subtitle: "도시 선교와 복음 중심주의 — 그의 유산을 돌아보다",
    accent: "#1E40AF",
    author: { name: "박성진 교수", title: "총신대학교 신학과" },
    readTime: 8,
    keywords: ["팀켈러", "도시선교", "복음주의", "리디머교회"],
    relatedLearnId: "c2",
  },
  {
    id: "ia4",
    category: "theology",
    categoryLabel: "신학&아카이브",
    label: "ARCHIVE",
    title: "마틴 루터의 종교개혁과\n오늘의 교회",
    subtitle: "1517년의 외침이 2026년에 던지는 질문",
    accent: "#1E40AF",
    author: { name: "이종훈 목사", title: "개혁신학연구원장" },
    readTime: 10,
    keywords: ["루터", "종교개혁", "95개조", "신앙"],
  },
  {
    id: "ia5",
    category: "book",
    categoryLabel: "기독교출판&서평",
    label: "BOOK REVIEW",
    title: "서평: 『묵상, 하나님의 음성 듣기』\n— 기도가 삶을 바꾸는가",
    subtitle: "데이비드 폴리슨 지음 | 큐티와 기도의 교차점에서",
    accent: "#7C3AED",
    author: { name: "오지영", title: "SOLT 매거진 에디터" },
    readTime: 6,
    keywords: ["묵상", "기도", "큐티", "서평"],
    relatedBookId: "s3",
    relatedLearnId: "2",
  },
  {
    id: "ia6",
    category: "book",
    categoryLabel: "기독교출판&서평",
    label: "BOOK REVIEW",
    title: "서평: 『하나님을 아는 지식』\n— J.I. 패커의 고전을 2026년에 읽다",
    subtitle: "반세기가 지나도 흔들리지 않는 신학의 뼈대",
    accent: "#7C3AED",
    author: { name: "한민준", title: "기독교 도서 리뷰어" },
    readTime: 7,
    keywords: ["패커", "신학", "고전", "하나님"],
    relatedBookId: "s1",
  },
  {
    id: "ia7",
    category: "lifestyle",
    categoryLabel: "크리스천라이프스타일",
    label: "LIFESTYLE",
    title: "크리스천 MZ세대,\n'건전한 놀이 문화'를 만들다",
    subtitle: "음주 없이 더 깊이 — SOLT 커뮤니티의 새로운 문화",
    accent: "#FF5C1A",
    author: { name: "SOLT 편집부", title: "문화 팀" },
    readTime: 4,
    keywords: ["MZ세대", "라이프스타일", "크리스천문화", "NonAlcoholic"],
    relatedLearnId: "1",
  },
  {
    id: "ia8",
    category: "lifestyle",
    categoryLabel: "크리스천라이프스타일",
    label: "CAREER",
    title: "직장 안에서 크리스천으로\n살아가기",
    subtitle: "신앙과 직업, 두 정체성 사이에서 균형 잡기",
    accent: "#FF5C1A",
    author: { name: "김지수", title: "직장선교네트워크 대표" },
    readTime: 5,
    keywords: ["직장선교", "믿음", "직업", "정체성"],
    relatedLearnId: "c3",
  },
];

// ── Profile ──
export const myProfile: ProfileData = {
  name: "김선호",
  church: "사랑의교회",
  bio: "빛과 소금으로 살아가는 기록",
  verse: "너는 내게 부르짖으라\n내가 네게 응답하겠고\n네가 알지 못하는 크고 은밀한 일을\n네게 보이리라",
  verseRef: "예레미야 33:3",
  essays: [
    { id: "e1", title: "새벽기도에서 만난 고요함", excerpt: "어둠 속에서 울린 찬양이 아침이 되었다.", date: "2026.02.28", emoji: "🌅", tag: "묵상" },
    { id: "e2", title: "선교지에서 보낸 편지", excerpt: "캄보디아의 아이들은 웃음으로 말했다.", date: "2026.02.14", emoji: "✈️", tag: "선교" },
    { id: "e3", title: "감사 일기: 300일째", excerpt: "매일 세 가지 감사를 기록하며 변한 것들.", date: "2026.01.30", emoji: "📝", tag: "일상" },
    { id: "e4", title: "내가 좋아하는 찬양 10곡", excerpt: "힘들 때 듣는 나만의 CCM 플레이리스트.", date: "2026.01.15", emoji: "🎵", tag: "찬양" },
    { id: "e5", title: "교회 안에서의 리더십", excerpt: "섬김의 리더십에 대해 배운 한 해.", date: "2025.12.28", emoji: "🕊️", tag: "성장" },
    { id: "e6", title: "크리스마스에 읽은 말씀", excerpt: "이사야 9장, 어둠 속에 빛이 비추었다.", date: "2025.12.25", emoji: "🎄", tag: "묵상" },
  ],
  beloved: [
    { id: "p1", name: "준혁", role: "소그룹 리더", word: "함께 달려가는 믿음의 동역자" },
    { id: "p2", name: "수빈", role: "멘토", word: "언제나 기도로 응원해주는 분" },
    { id: "p3", name: "민지", role: "독서 파트너", word: "말씀으로 대화하는 친구" },
    { id: "p4", name: "재원", role: "찬양팀", word: "찬양으로 하나 되는 시간" },
    { id: "p5", name: "하은", role: "러닝 크루", word: "새벽을 함께 여는 사람" },
  ],
  favoriteGoods: [
    shopItems[0],
    shopItems[2],
    shopItems[3],
    shopItems[5],
  ],
};
